### ISSUE TITLE
Remove godep from the coding standards

### ISSUE THREAD

**Issue by arschles** [deis/deis.io#149]
The [coding standards](http://docs.deis.io/en/latest/contributing/standards/#code-standards) for Go code prescribe godep, but all of our v2 Go codebases use [glide](https://github.com/Masterminds/glide). Since that seems to be the de-facto standard, change the docs to prescribe glide.

**Comment by bacongobbler** [comment]
@arschles I'm pretty sure this has been updated in docs-v2: https://github.com/deis/docs-v2/blob/master/src/contributing/development-environment.md#prerequisites :)

**Comment by arschles** [comment]
Got it, thanks @bacongobbler. Closing
