### ISSUE TITLE
No public repository for the deis.com site

### ISSUE THREAD

**Issue by nathansamson** [deis/deis.io#169]
Not sure if this is the best repository to mention this, but I was looking for the repo for the deis.com website.

Reasoning is that I wanted to change some styling.

Not sure if this repo is just forgotten to be published or it is on purpose...

In case you are wondering, I am not a huge fan of the hovers over figure/pre blocks as seen on "https://deis.com/blog/2016/deis-workflow-basics-pt-3/". The appearing border is nice, but the moving text is quite irritating.

**Comment by slack** [comment]
We haven't made the deis.com site public, but thanks for the feedback! I'll pass it along.
