### ISSUE TITLE
Permission denied on deis-client 2.1.0 used on dpl lib for Travis deploy.

### ISSUE THREAD

**Issue by lzerma** [deis/deis.io#181]
Hey guys, 

I'm trying to deploy applications using deis module on travis.ci and I came across with this problem: 

```
Installing deploy dependencies
Fetching: git-1.3.0.gem (100%)
Successfully installed git-1.3.0
1 gem installed
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (22) The requested URL returned error: 403
dpl.2
Preparing deploy
No stash found.
Login failed.
failed to deploy
```
I ran some debugs and found that the deis-cli with the version that I'm using isn't sufficient permissions on S3 to be downloaded on DPL library.
```curl -sSL https://s3-us-west-2.amazonaws.com/get-deis/deis-cli-2.1.0-darwin-amd64.run```

**Comment by Joshua-Anderson** [comment]
@lzerma This is because dpl is trying to install the v2 CLI using the v1 installation script. Dpl has a PR to support dpl v2 at travis-ci/dpl#440 but it's still waiting to be merged.

Since this is a dpl problem, and not an installation script problem, I'm going to close the issue here.
