### ISSUE TITLE
Can't download Deis client

### ISSUE THREAD

**Issue by onbjerg** [deis/deis.io#85]
Going to http://docs.deis.io/en/v0.9.0/developer/install-client/ and downloading a client gives a HTTP error of 403.

Also the same with the install script provided in the documentation.

**Comment by bacongobbler** [comment]
That's for a v0.9.0 client. You may want to try something a little more updated: http://docs.deis.io/en/latest/using_deis/install-client/

**Comment by onbjerg** [comment]
I've used that script as well, but I get a 403 on that, too.

```
$ curl -sSL http://deis.io/deis-cli/install.sh | sh
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (22) The requested URL returned error: 403 Forbidden
```

**Comment by mboersma** [comment]
In the S3 bucket we only have Deis v1.0 and later clients, and none for Windows. :disappointed: The `install.sh` script is pretty simplistic in generating a URL, but on Windows I'm sure what it generates doesn't exist for download:
```console
# determine from whence to download the installer
PLATFORM=`uname | tr '[:upper:]' '[:lower:]'`
DEIS_INSTALLER=${DEIS_INSTALLER:-deis-cli-$VERSION-$PLATFORM-amd64.run}
DEIS_BASE_URL=${DEIS_BASE_URL:-https://s3-us-west-2.amazonaws.com/opdemand}
INSTALLER_URL=$DEIS_BASE_URL/$DEIS_INSTALLER
```

**Comment by bacongobbler** [comment]
Note that this is a standalone client built using makeself. Alternatively, you can use `pip install deis` to install the client or build from source via `pip install client/`.

**Comment by onbjerg** [comment]
So basically Deis is useless on Windows hosts until Deis makes a new release and deis-ui works? @mboersma

**Comment by mboersma** [comment]
@onbjerg the `deis` command-line interface should work on Windows, we just don't package it for download. `pip install deis` should do the trick on a Windows platform with Python installed, but that's just the developer CLI, not the whole enchilada.

I'm going to close this issue, but please open a new one over in [deis/deis](https://github.com/deis/deis/) if you have ideas for testing, building, or packaging `deis` for Windows. We have tested it in the past but haven't had the bandwidth to do so often, or to support it. And our current installer solution [`makeself`](https://github.com/deis/makeself) is a UNIX-only kind of thing.

**Comment by onbjerg** [comment]
Okay, I will try to think of something. It's not that high of a priority, though, I'm just gonna use Linux :stuck_out_tongue:
